dist: xenial

os: linux

language: generic

services:
  - docker

before_install:
  - docker build -f Dockerfile.dev  -t jvrh/docker-teste .

script:
  - docker run -e CI=true jvrh/docker-teste npm run test
    
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep_history: true
  on:
    branch: master
