dist: xenial

os: linux

language: generic

services:
  - docker
  - npm

before_install:
  - docker build -t jvrh/docker-teste .

script:
  - docker run -e CI=true jvrh/docker-teste npm run test
  - npm run build
    
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep_history: true
  on:
    branch: master
