dist: xenial

os: linux

language: node_js

services:
  -npm

before_install:
  -npm install

script:
  -CI=true npm run test

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep_history: true
  on:
    branch: master
